version: '3.9'

services:
  postgres:
    image: postgres:latest
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - mynetwork 

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes: 
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://user:password@postgres/mydatabase
    ports: 
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - mynetwork
      
networks:
  mynetwork:   

volumes: # docker, você vai poder olhar este path e criar um arquivo aqui de forma permanente
  postgres_data:

