version: '3.8'

services:
  postgres:
    image: postgres:latest
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - mynetwork 
      
networks:
  mynetwork:   

volumes: # docker, você vai poder olhar este path e criar um arquivo aqui de forma permanente
  postgres_data:

